name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v3 

      - name: Ensure backend bucket exists
        run: |
          aws s3api head-bucket --bucket terraform-cicd-aws-infra-s3-bucket || \
          aws s3api create-bucket --bucket terraform-cicd-aws-infra-s3-bucket --region us-east-1

      - name: Terraform Init
        working-directory: environments/dev 
        run: terraform init
      
      - name: Terraform Format
        working-directory: environments/dev
        run: terraform fmt -recursive
      
      - name: Terraform Plan 
        working-directory: environments/dev
        run: terraform plan -input=false -var-file="dev.tfvars"

      - name: Terraform Apply 
        working-directory: environments/dev
        run: terraform apply -auto-approve -input=false -var-file="dev.tfvars"
      
      - name: Terraform Clean up  
        working-directory: environments/dev
        run: terraform destroy -auto-approve -input=false -var-file="dev.tfvars"
